language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

install:
  - GO111MODULE=off go get github.com/mattn/goveralls

os:
  - linux

script:
  - go test -race -v
  - $HOME/gopath/bin/goveralls -service=travis-ci
